language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm run build

after_script:
  - cd ./build
  - git init
  - git config user.name "stone310"
  - git config user.email "pom31000@163.com"
  - git add .
  - git commit -m "Update"
  - git remote add master git@github.com:stone310/test.git
  - git push --force --quiet -u master master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: 1
